---
# ------------------------- #
# Input Files Customization #
# ------------------------- #

#input files template
TEMPL1: ginput.tmpl

METHODS:
- M062X

BASES:
- def2-QZVPPD

#Number of processors for parallel jobs
PROC: 1

#If you don't use this, leave it blank and don't comment it out, otherwise it will result in an error.
OTHERS: RHF

# ------------------ #
# Directory location #
# ------------------ #

#Directory containing all xyz files (full or relative path)
GEOMETRIES_DIR: /home/kostya_2100/knvvv/ACCDB/Geometries

#Directory where the output file structures is created (full or relative path)
OUTPUTS_DIR: /home/kostya_2100/knvvv/ACCDB/Automation/output

#Directory containing the list of databases/subsets that needs to be run (they can be more than one)
MOL_LIST_DIR: /home/kostya_2100/knvvv/ACCDB/Automation

# ---------------- #
# Running the jobs #
# ---------------- #

#Call to the quantum chemistry program
QCENGINE_CALL: "echo lol"   #Q-Chem
          # "g16 {input} {output}"                 #Gaussian
          
#regexp to extract final energies from output files
REGEXP: 'FINAL KOHN-SHAM ENERGY:\s+' #Q-CHEM
      # 'SCF Done:  E({method}) =  '                # Gaussian

...
